version: '3.9'

services:
  mssql:
    container_name: mssql
    hostname: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=AreY0uD0neW1thCW!
      - MSSQL_PID=Express
  mssqlsetup:
    image: mcr.microsoft.com/mssql/server:2022-latest
    depends_on:
      - mssql
    restart: "always"
    entrypoint: [ "bash", "-c", "sleep 10 && /init.sh && /create.sh"]
    volumes:
      - ./init.sh:/init.sh
      - ./init.sql:/init.sql
      - ./create.sh:/create.sh
      - ./create.sql:/create.sql
